<?php
/*********************************************************************
 * Extension configuration file for ext "pagepath".
 *
 * Generated by ext 14-02-2014 11:33 UTC
 *
 * https://github.com/t3elmar/Ext
 *********************************************************************/
$EM_CONF[$_EXTKEY] = array(
    'title'            => 'Page path',
    'description'      => 'Provides API for Backend modules to get a proper path to the Frontend page (simulateStatic/RealURL/CoolURI-like)',
    'category'         => 'be',
    'author'           => 'Dmitry Dulepov',
    'author_email'     => 'dmitry@typo3.org',
    'shy'              => '',
    'dependencies'     => '',
    'conflicts'        => '',
    'priority'         => '',
    'module'           => '',
    'state'            => 'stable',
    'internal'         => '',
    'uploadfolder'     => 0,
    'createDirs'       => '',
    'modify_tables'    => '',
    'clearCacheOnLoad' => 0,
    'lockType'         => '',
    'author_company'   => '',
    'version'          => '2.0.0',
    'constraints'      =>
        array(
            'depends'   =>
                array(
                    'typo3' => '6.2.0-7.6.999',
                    'php'   => '5.6.0-6.0.0',
                ),
            'conflicts' =>
                array(),
            'suggests'  =>
                array(),
        ),
    'suggests'         =>
        array(),
    'autoload'         => array(
        'psr-4' => array(
            'Dmitryd\\Pagepath\\' => 'Classes'
        )
    ),
);
?>
